### ISSUE TITLE
Web server configuration for multiple iSB on one server

### ISSUE THREAD

**Issue by datadavev** [isamplesorg/isamples_inabox#106]
Multiple iSB instance may be run on a single server as separate docker containers. Each exposes the web API through a different port, however it is desirable to access each through a standard port (443 for HTTPS).

This can be achieved with a reverse proxy service on the container host. There are basically two common patterns for this:

1. Use a virtual host per iSB instance. e.g. `sesar.isb.isample.xyz`, `geome.isb.isample.xyz` ...
2. Map the ports to paths, e.g. `isb.isample.xyz/sesar`, `isb.isample.xyz/geome` ...

**Comment by datadavev** [comment]
Option 1 requires DNS management for each virtual host as well as corresponding certificate management. Both are straight forward though (currently) require manual steps for management.

Option 2 can use a single DNS entry with corresponding certificate and can be managed in a single location in the web server config.

Suggest option 2 as the approach to take.

**Comment by datadavev** [comment]
Web server choices include Apache and Nginx, with Nginx apparently more performant with large numbers of connections. Suggest using nginx as the web server.

Configuration will generally take the pattern:
```
location /opencontext/ {
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-Scheme $scheme;
  proxy_set_header X-Forwarded-Host $server_name;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
  proxy_redirect off;
  proxy_buffering off;
  proxy_http_version 1.1;
  proxy_pass http://localhost:8000;
}
```

**Comment by datadavev** [comment]
Certificates re provided by letsencrypt. Setup:

```
sudo apt install certbot python3-certbot-nginx
sudo certbot 
# answers:
# email address
# nginx
# henry.cyverse.org isb.isample.xyz
# redirect all to https
```

**Comment by dannymandel** [comment]
@datadavev isn't this how we've deployed the multiple iSB instances on henry?  Do we still need this issue?

**Comment by datadavev** [comment]
Yep, all good now.
