### ISSUE TITLE
Ajaxfiltering and AjaxSorting

### ISSUE THREAD

**Issue by qgan7125** [isamplesorg/isamples_inabox#11]
For the server-side, I don't think the server handles the filters and sorters parameters in the query parameter in the tabulator request. So the tabulator could not use filtering and sorting on the server-side. The UI implementation could just use them locally.

One question: Why the APi (https://mars.cyverse.org/thing/?offset=0&limit=1000&status=200) always return the different data every time the web calls it, even though the offset and limit parameters aren't changed?

**Comment by datadavev** [comment]
Filtering can be added to the server. Document the request and expected response.

The API had a bug that prevented consistent sorting of the responses. It is corrected now.

**Comment by datadavev** [comment]
Implemented with connection to solr
