### ISSUE TITLE
Github  authentication and Post issues

### ISSUE THREAD

**Issue by qgan7125** [isamplesorg/isamples_inabox#14]
Figure out how to authenticate a user on iSamples UI into github, so the bug report the user generates can pass github authentication process and be posted in github.

**Comment by qgan7125** [comment]
https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#redirect-urls
Github Oauth app documentation

**Comment by datadavev** [comment]
Options here include using GH PAT with local browser storage, which may be better for technical work. Certainly lighter weight than full OAuth workflow.

**Comment by dannymandel** [comment]
We aren't using GitHub for this anymore.  This has been superseded by ORCID.  Closing.
