### ISSUE TITLE
Authenticate a command line client using ORCID

### ISSUE THREAD

**Issue by datadavev** [isamplesorg/isamples_inabox#163]
The goal here is to allow access to an endpoint on the fastAPI service to trusted users only.

We would like to use ORCID as the identify provider.

The user will use credentials provided from ORCID when calling fastAPI to assert their identity. FastAPI will verify the credentials, probably by calling ORCID to verify the token is valid.

Reference:
* https://oauth.net/2/
* https://aaronparecki.com/oauth-2-simplified/
* https://info.orcid.org/documentation/api-tutorials/api-tutorial-get-and-authenticated-orcid-id/

**Comment by dannymandel** [comment]
~~This looks like something that might work for our API requests: https://developer.okta.com/blog/2018/07/16/oauth-2-command-line~~ -- on further reading it is interesting but probably not the right way to do this

**Comment by dannymandel** [comment]
There are some good diagrams of the overall flow here: https://developer.okta.com/blog/2019/08/22/okta-authjs-pkce

**Comment by dannymandel** [comment]
Though maybe, now that I think about it, the script that will be minting identifiers *could* start up a local web server.  Might be worth prototyping.  We'd definitely need to go the PKCE route there, though, as we wouldn't want our private keys embedded anywhere.

**Comment by datadavev** [comment]
I believe we are looking at the 3-legged flow. https://info.orcid.org/documentation/integration-and-api-faq/#easy-faq-2537

The workflow might be something like this:
![workflow](http://www.plantuml.com/plantuml/svg/bP91Q_Cm38Rl_XKwfj2czqA-hxJReNIii7NGMp6sceebTd7K5VRhPmKJ4k-qIx2iHw_yAbfth0FVsqPfmpx0HuT1tU8L6Rffnq3lcqbyUDlkdfIgAjW4_uWqL9MIAbZy4tW5DVBHVw8hPYh6i8Ztabz1G4i13OCFXcpfGxtq-ixNfNnye6yiJ4Fe-4nsFj3dcwvn3cLPpeO-_IDMyCVglchqdiRNv420NBZFvFoWAJQd3VuRRx4wdKxJIGZp6ucfKQiq0fQ9ZGsaOuSc8CSmLMTMKgFZOV_ycarRciA3-0gzDf2xUEKy8_WlJ3zQFc2q0xv6ujwX7CQyrCiTHSothNOM6dAONgSmnY8fwx1zsUMh85ZPakETZJHT24FHYy_o8GJKjkZNOY7c4vIvFEobR10NOQ11ERC_IgWrEXjN_0S0)

**Comment by dannymandel** [comment]
I can start working on making the changes to validate the token in the identifier minting code.

**Comment by dannymandel** [comment]
I think is more or less working?

**Comment by datadavev** [comment]
yep, this is working. closing.
