### ISSUE TITLE
Metadata enhancement using classifiers 

### ISSUE THREAD

**Issue by hyunssong** [isamplesorg/isamples_inabox#168]
To use the classifiers that are trained to fill in the blanks of the dataset, 

For the existing source dataset:
1. Run the classifiers on it through hpc. The source dataset will contain text fields that will be used as input to the model.
2. The model classification result (id, predicted label and its probability) on each record will be sent to @dannymandel and these results will be added to the `solr` database as a field. The database would need additional fields such as the predicted label, probability, and the subject who created the label (human /machine predicted).

For new records that will be added by the user:
1. The classifier will be loaded and predict the label for the empty fields.

**Comment by dannymandel** [comment]
@hyunssong is this still an issue?

**Comment by hyunssong** [comment]
This issue was opened to start the process of training metadata models. The details and code of the training process are in the `content-classification` repo, so I will close this issue.
