### ISSUE TITLE
Support different record views using Content Negotiation by Profile

### ISSUE THREAD

**Issue by datadavev** [isamplesorg/isamples_inabox#187]
ISamples supports two fundamentally different views of each record: the original as retrieved from the source and the record as transformed ti the isamples model.

An emerging standard mechanism for requesting different views of the same resource is described in the W3C draft standard: "[Content Negotiation by Profile](https://www.w3.org/TR/dx-prof-conneg/)" specification.

iSamples in a box should support this functionality for at least two operations: 

1. The existing `/thing/{identifier}` "get thing" operation 

2. A new operation `/resolve/{identifier}` "resolve identifier", which given the same parameters as get thing, returns the URL to retrieve the record as a `302 Found` response with the URL provided in the `Location` response header (i.e. a redirect) unless the client provides a custom request header `Do-Redirect` with a value of `0` or `false`, in which case the response is the same except with a status of `200 OK`. (This option is necessary for browser clients to receive the location information without following the returned location header).

For profiles, let's start with no profile specified, default to the original record. If a profile of "https://w3id.org/isample/schema" is specified, then the response should be the isamples record structure. Additional profiles may be specified in the future (not many though, likely less than 5).

An existing library [pyLDAPI](https://github.com/RDFLib/pyLDAPI) can be leveraged (or pieces reused) to implement the functionality.

**Comment by dannymandel** [comment]
For the original record, do we have a URI for the profile?  In the spec it indicates that every profile should have a URI associated with it.  We clearly have one for iSamples (the one you mentioned up above), but I think we are supposed to include a header that indicates it's in the original profile if we are to be fully conforming to the spec.

**Comment by datadavev** [comment]
Good point. Technically we should use a URI that references a concept like "this is the unadulterated source of the record" defined in some published ontology. For now, let's use `https://w3id.org/isample/source_record` though this will likely be replaced with some existing definition when we find it.

**Comment by dannymandel** [comment]
@datadavev are we good to close this one?
