### ISSUE TITLE
Experimental: Implement a minimal Git backed, iSB harvestable record source.

### ISSUE THREAD

**Issue by datadavev** [isamplesorg/isamples_inabox#198]
There is a need for a simple system to support field data collection in an offline-first system that enables content creation and editing with no Internet connection, but is able to seamlessly participate in the iSamples network when a network connection becomes available.

This experiment will leverage CSV for file storage, git for revision control, GitHub for serving static content, and if necessary, supporting services operating within the constraints of zero-cost hosting such as on Deta, Vercel, Google App Engine, or AWS.

## Workflow

The workflow might be something like:

1. A GitHub repository is created based on a template that includes necessary actions and structure.
2. User creates a spreadsheet containing their data
3. User commits spreadsheet to local repo. Validation is run as part of the commit, or separately via script.
4. The spreadsheet is pushed to GitHub
5. A GH action parses the sheet and generates iSamples JSON entries for each record, an XML sitemap for the records, and publishes them on the `gh-pages` branch of the repository.
6. An iSB instance harvests and indexes the content.

## Some Questions

- Best place to assign identifiers? 
    - Ideally identifiers should be available at the time of content entry, so perhaps the repo includes a script that generates a spreadsheet template with requested number of pre-allocated identifiers?
- How far can we go with providing some sort of UI for the content, hosted on GH, zero-cost service, or perhaps just running locally with Docker etc?

**Comment by dannymandel** [comment]
Presumably the identifiers would be allocated via datacite before they went to do fieldwork?

**Comment by datadavev** [comment]
Yep, that would be best, though field work is typically a messy business. Another option may be to have the first part of the identifier available and unique to the sheet, and each row incrementing a suffix as needed. Then each record has a unique identifier but isn't registered until the sheet is committed. I'm not sure which is best from the user perspective.

**Comment by dannymandel** [comment]
I think it will be less problematic overall to make registering N drafts a requirement before beginning the process.  

On the one hand, it makes more work up front but on the other it is going to save user headaches down the road by us not having to anticipate every manual algorithm someone could come up with.

**Comment by datadavev** [comment]
Yep, that will definitely be less problematic for processing. We may need to adjust after some folks try the approach in the field though. Hard to say without testing where flexibility might be useful - so we can certainly go with the pre-registered approach first.

**Comment by dannymandel** [comment]
re: the UI and everything -- I did that work a while back to write an ansible script that set up a Multipass Linux VM that in theory could run Docker in the field.  I don't remember where I left it, but in theory it *could* run the whole thing.

**Comment by dannymandel** [comment]
@datadavev are we good to close this one?
