### ISSUE TITLE
Incorrect config for SESAR models in isb_web_config.env

### ISSUE THREAD

**Issue by dannymandel** [isamplesorg/isamples_inabox#242]
The SESAR models config says they should live at `/app/metadata_models/SESAR_material_config.json`.  When the container is actually built, they live at `/app/metadata_models/models/SESAR_material_config.json`.

**Comment by dannymandel** [comment]
It looks like this error is in the `.json` config file as well -- that file needs to have the `/models` path component inserted into it as well.

**Comment by dannymandel** [comment]
Additional error in OpenContext:

```
it looks like /app/metadata_models/models/opencontext-material is not the path to a directory containing a config.json file.
```

**Comment by dannymandel** [comment]
Confirmed that that directory doesn't exist:

```
root@0515591ebdec:/app# ls /app/metadata_models/models/
OPENCONTEXT_material_config.json  OPENCONTEXT_material_config.json~  OPENCONTEXT_sample_config.json  OPENCONTEXT_sample_config.json~  SESAR_material_config.json  opencontext-sample  sesar-material
```

**Comment by dannymandel** [comment]
@hyunssong What is the expected state of the OpenContext-material model right now?  It looks like that directory doesn't exist and it is throwing an exception when running the indexer.

**Comment by hyunssong** [comment]
@dannymandel I just created a pull request for the .env files in the` isamples_docker` repo, and uploaded the updated state of the `opencontext-material` model. Sorry for the confusion.

**Comment by dannymandel** [comment]
Closing this one due to fix by @hyunssong.  Thanks Sarah!
