### ISSUE TITLE
Missing a few hundred records in solr index

### ISSUE THREAD

**Issue by dannymandel** [isamplesorg/isamples_inabox#26]
Looks like we're a few hundred records short in the solr index:

db:
```
isb_1=> select count(*) from thing where authority_id='SESAR';
  count  
---------
 1784731
```

solr:
```
isamples@mars:~$ curl http://localhost:8983/solr/isb_core_records/select?q=*%3A*
{
  "responseHeader":{
    "zkConnected":true,
    "status":0,
    "QTime":34,
    "params":{
      "q":"*:*"}},
  "response":{"numFound":1784478
```

**Comment by dannymandel** [comment]
This actually ends up having a pretty reasonable explanation.  For solr, we use the value of `sampleidentifier` in the iSample Core Metadata record as the id field.  In the case of SESAR, that's this:

```
    def sample_identifier_value(self) -> typing.AnyStr:
        return self.source_record["igsn"]
```

In looking at the database, we see the following:

```
isb_1=> select count(distinct resolved_content->'igsn') from thing where authority_id='SESAR';
  count  
---------
 1784478
(1 row)
```

vs. all the records:

```
isb_1=> select count(*) from thing where authority_id='SESAR';
  count  
---------
 1784731
(1 row)
```

so the number of records in the solr instance is equal to the number of distinct IGSN values in the database.  Why are there duplicate records for a single IGSN ?  Is that expected?

**Comment by dannymandel** [comment]
Per discussion with @datadavev this is because there are a couple hundred or so records that failed to be retrieved from SESAR.  So, they have a record in thing, but they have no associated `resolved_content` so they won't get added to Solr.

**Comment by dannymandel** [comment]
```
isb_1=# select count(*) from thing where authority_id='SESAR' AND id != CONCAT('IGSN:', resolved_content->>'igsn');
 count
-------
   253


isb_1=# select count(*) from thing where resolved_status != 200;
 count
-------
   253
```

**Comment by dannymandel** [comment]
So, I'm not sure there's anything to do here -- at least not on the solr side.  If anything, we could investigate why records weren't resolved from SESAR, but this might be expected.  What do you think @datadavev?

**Comment by datadavev** [comment]
Nothing to do here except support reloading failed retrieval attempts. See #33
