### ISSUE TITLE
Add GEOME children to the solr relations core

### ISSUE THREAD

**Issue by dannymandel** [isamplesorg/isamples_inabox#30]
Quoting @datadavev 

>  It’s fairly simple with basically a triple of subject, predicate, object. Subject in this case would be the id of the record, predicate “subsample” and object the target value.

**Comment by dannymandel** [comment]
I wonder if this might already be done?

```
{
        "source":"ark:/21547/Cev2SZOO_0177",
        "s":"ark:/21547/Cev2SZOO_0177",
        "p":"has_tissue",
        "o":"ark:/21547/Cex2SLAB87067.1",
        "name":"",
        "id":"ebf0fdf11eb1a517978a938e0e03a41f",
        "tstamp":"2021-06-01T12:14:24.677Z",
        "_version_":1701366640836345859},
```

**Comment by dannymandel** [comment]
@datadavev could you either close this one if its done or tell me what we want to do differently compared to what we've already done?  Thanks.

**Comment by datadavev** [comment]
Implemented in https://github.com/isamplesorg/isamples_inabox/blob/main/scripts/geome_things.py and https://github.com/isamplesorg/isamples_inabox/blob/main/isb_lib/geome_adapter.py
