### ISSUE TITLE
samplingSite is the only key that is still camel-cased, should it be snake case?

### ISSUE THREAD

**Issue by dannymandel** [isamplesorg/isamples_inabox#307]
In all the OC 1.0 JSON files, the `samplingSite` key is still camel-cased.  Everything else has been converted to snake case.  Is this a mistake or is there a legitimate reason we want this to be different from the rest?

https://github.com/isamplesorg/metadata/blob/264a71947b05cdb3a7ffad8303be43039a681ea6/examples/OpenContext/test1.0Valid/ark-28722-k2d511s24-v1.json#L59

**Comment by dannymandel** [comment]
It looks like `relatedResource` and `relationshipType` are also camel-case:

```
    "relatedResource": [
        {
            "label": "child tissue sample LACM:DISCO:16924:9597",
            "description": "",
            "target": "ark:/21547/DRY2LACM:DISCO:16924:9597",
            "relationshipType": "subsample"
        },
        {
            "label": "child tissue sample LACM:DISCO:16924.2",
            "description": "",
            "target": "ark:/21547/DRY2LACM:DISCO:16924.2",
            "relationshipType": "subsample"
        }
    ]
```
https://github.com/isamplesorg/metadata/blob/264a71947b05cdb3a7ffad8303be43039a681ea6/examples/GEOME/test1.0Valid/ark-21547-DRW2LACM-DISCO-16924-v1.json#L110C1-L123C6

Please confirm if they should be the exception or be converted to snake case.

**Comment by smrgeoinfo** [comment]
should be sampling_site, and related_resource/relationship (not relationshipType).  Interesting that the JSON schema validator in Oxygen didn't catch these....
