### ISSUE TITLE
A couple of missing values in the previous transformation rules

### ISSUE THREAD

**Issue by dannymandel** [isamplesorg/isamples_inabox#310]
When porting the old code to the new controlled vocabularies, I noticed the following:

```
    _soilFloodplainMapper = StringPairedCategoryMapper(
        "Microbiology>Soil", "floodplain", "Subaerial terrestrial biome", vocabulary_mapper.SAMPLED_FEATURE
    )
```

and `Subaerial terrestrial biome` doesn't appear in sampledfeature.txt (https://github.com/isamplesorg/isamples_inabox/blob/new_metadata_format/isamples_metadata/vocabularies/sampledfeature.txt)

What should be used instead?

Similarly, `Marine biome` is gone from here:

```
_ventBiologyMapper = StringPairedCategoryMapper("Biology", "Vent", "Marine biome", vocabulary_mapper.SAMPLED_FEATURE)
```

(also expecting to find it here: https://github.com/isamplesorg/isamples_inabox/blob/new_metadata_format/isamples_metadata/vocabularies/sampledfeature.txt)

What should we use instead?

**Comment by smrgeoinfo** [comment]
marine biome is now "Marine environment" https://w3id.org/isample/vocabulary/sampledfeature/0.9/marinewaterbody

subaerial terrestrial biome is "Subaerial surface environment"
https://w3id.org/isample/vocabulary/sampledfeature/0.9/subaerialsurfaceenvironment

**Comment by dannymandel** [comment]
Thank you!
