### ISSUE TITLE
make analytics messages non-blocking

### ISSUE THREAD

**Issue by datadavev** [isamplesorg/isamples_inabox#321]
When diagnosing slow response on hyde after migration from aws the responsiveness of calls like `/things/select` was very slow although solr was fast. The problem was a blocking call to the metrics service which needed to time out before continuing. 

The metrics calls should be non-blocking. We can probably use the fastapi `BackgroundTask` for this, and probably add it as  middleware so it is automatically part of all method calls.

**Comment by dannymandel** [comment]
This was fixed with https://github.com/isamplesorg/isamples_inabox/pull/330
