### ISSUE TITLE
Consolidate identifiers amongst providers and in between Things db and Solr index

### ISSUE THREAD

**Issue by dannymandel** [isamplesorg/isamples_inabox#52]
We have a few different representations of identifiers in two different places, the Things table, and the Solr index.  They are inconsistent between providers and between the database and Solr index.  We should clean this up.  We want the id column in the Things db and the id column in the Solr schema to be the same thing.

The following are the values we want to use:

-- For SESAR, use the IGSN as it exists in the Things db.

```

isb_1=> select id from thing where authority_id='SESAR' order by _id desc limit 1;
       id       
----------------
 IGSN:SIO0000H9
```

Currently in Solr it is lowercased:

```
"id":"igsn:NHB002NH6",
```

Fix that.

-- For GEOME, both the Things database and the Solr index have the correct ark values:

```
isb_1=> select id from thing where authority_id='GEOME' limit 1;
            id             
---------------------------
 ark:/21547/Dei2BOMAN_3342
```

-- For Smithsonian, the Solr value looks correct, but we need to fix the database:

```
isb_1=> select id from thing where authority_id='SMITHSONIAN' limit 1;
                               id                                
-----------------------------------------------------------------
 http://n2t.net/ark:/65665/3dcf6c620-b14b-4447-9286-9360513b8ee5
```

It should match the GEOME format we are using there.

-- For OpenContext, @datadavev is going to open a separate issue to work with @ekansa about how we want to handle it.

**Comment by datadavev** [comment]
See also #53

**Comment by dannymandel** [comment]
Merged and fixed the remaining issues.  Going to close this one out.
