### ISSUE TITLE
Failing tests in test_sesar.py

### ISSUE THREAD

**Issue by dannymandel** [isamplesorg/isamples_inabox#60]
As part of turning on the PR tests, I noticed that `test_sesar.py` was no longer compiling due to a rename.  I fixed that, but then went to run the tests and they all failed.  I marked them as `@pytest.mark.xfail` so they wouldn't break the build, but is there any value in keeping them or should we just delete the file?

**Comment by datadavev** [comment]
Those tests aren't very useful, especially as unit tests. OK to delete.

**Comment by dannymandel** [comment]
Deleted them.
