### ISSUE TITLE
iSamples API missing child Thing records, while they're available in Solr

### ISSUE THREAD

**Issue by dannymandel** [isamplesorg/isamples_inabox#68]
Per discussion with @datadavev:

> One thing I’ve noticed is that we have a disparity between solr records and “thing” records for GEOME and OpenContext sources.

This is because we are generating core records for sub-records, which is what was intended, but causes a situation where the identifier in solr can’t be used to get the record from the database using the API.

For example, the GEOME record ark:/21547/CYR2envbio08_98 is in solr and can be access via the API at thing/ark:/21547/CYR2envbio08_98. However the child of that record, ark:/21547/CYT2MBIO16729.1 can be found by solr, but not through the API.

This is a fairly fundamental issue with the content representation differences across the collections, and something that the “relations” collection in solr can be used for.

Option are basically: 1) store each of the record components as separate records in the things collection (so that GEOME would have an a sample and a tissue record) or 2) provide a lookup to the parent record by following relations (e.g. o:ark\:\/21547\/CYT2MBIO16729\.1 returns the source record id).

Both approaches have issues, but I think #1 provides the simplest way to get consistent representation across the collections. This would mean that for GEOME records, we would have Event, Sample, and Tissue records in things. The Event would be used to populate the location and time collected information for the Sample and Tissue core records that get added to Solr. Conceptually, both the “Sample” and “Tissue” records are different types of physical samples, and they share a common collection event. This is similar to how the SESAR records are presented (with their parent / child records).

**Comment by dannymandel** [comment]
Here's one example

```
{
    "parent": {
        "bcid": "ark:/21547/BIE2391b18d0c39141193a2379f36b77e539",
        "entity": "Event",
        "country": "USA",
        "eventID": "391b18d0c39141193a2379f36b77e539",
        "locality": "French Frigate Shoals",
        "projectId": "1",
        "stateProvince": "Hawaii",
        "yearCollected": "2006",
        "expeditionCode": "chamul_CYB_mc",
        "decimalLatitude": "23.7502778",
        "decimalLongitude": "-166.1666667",
        "principalInvestigator": "Rob Toonen"
    },
    "record": {
        "bcid": "ark:/21547/mx2CMU_161",
        "genus": "Chaetodon",
        "entity": "Sample",
        "phylum": "Chordata",
        "eventID": "391b18d0c39141193a2379f36b77e539",
        "wormsID": "273349",
        "projectId": "1",
        "expeditionCode": "chamul_CYB_mc",
        "specificEpithet": "multicinctus",
        "materialSampleID": "CMU_161",
        "identificationRemarks": "Morphology"
    },
    "children": [
        {
            "bcid": "ark:/21547/BIF2CMU_161",
            "entity": "Tissue",
            "tissueID": "CMU_161",
            "projectId": "1",
            "expeditionCode": "chamul_CYB_mc",
            "materialSampleID": "CMU_161"
        }
    ],
    "projectId": 1
}
```

**Comment by dannymandel** [comment]
Which ends up with this in Solr (using the query id:"ark:/21547/mx2CMU_161"):

```
      {
        "id":"ark:/21547/mx2CMU_161",
        "isb_core_id":"metadata/21547/mx2CMU_161",
        "indexUpdatedTime":"2021-09-29T21:51:21.136Z",
        "label":"CMU_161",
        "description":"identificationRemarks: Morphology",
        "description_text":["identificationRemarks: Morphology"],
        "hasMaterialCategory":["Organic material"],
        "hasSpecimenCategory":["Whole organism"],
        "keywords":["Hawaii",
          "USA",
          "Chordata"],
        "informalClassification":["Chaetodon",
          "multicinctus"],
        "producedBy_label":"391b18d0c39141193a2379f36b77e539 chamul_CYB_mc",
        "producedBy_description":"expeditionCode: chamul_CYB_mc | projectId: 1",
        "producedBy_description_text":["expeditionCode: chamul_CYB_mc | projectId: 1"],
        "producedBy_responsibility":["principalInvestigator: Rob Toonen"],
        "producedBy_resultTime":"2006-01-01T00:00:00Z",
        "producedBy_isb_core_id":"ark:/21547/BIE2391b18d0c39141193a2379f36b77e539",
        "producedBy_samplingSite_label":"French Frigate Shoals",
        "producedBy_samplingSite_placeName":["French Frigate Shoals",
          "Hawaii",
          "USA"],
        "producedBy_samplingSite_location_ll":"23.7502778,-166.1666667",
        "producedBy_samplingSite_location_bb":"ENVELOPE(-166.1666667, -166.1666667, 23.7502778, 23.7502778)",
        "producedBy_samplingSite_location_rpt":"POINT (-166.1666667 23.7502778)",
        "relatedResource_isb_core_id":["ark:/21547/BIF2CMU_161"],
        "source":"GEOME",
        "producedBy_samplingSite_location_bb__minY":23.7502778,
        "producedBy_samplingSite_location_bb__maxX":-166.1666667,
        "_version_":1712274571225202689,
        "producedBy_samplingSite_location_bb__minX":-166.1666667,
        "producedBy_samplingSite_location_bb__maxY":23.7502778}]
  }
```

But if you look for the parent id: `ark:/21547/BIE2391b18d0c39141193a2379f36b77e539`, we don't find it.  If you look for the child `id:"ark:/21547/BIF2CMU_161"`, we get this:

```
{
        "id":"ark:/21547/BIF2CMU_161",
        "isb_core_id":"metadata/21547/BIF2CMU_161",
        "indexUpdatedTime":"2021-09-29T21:51:21.137Z",
        "label":"CMU_161",
        "hasMaterialCategory":["Organic material"],
        "hasSpecimenCategory":["Organism part"],
        "keywords":["Hawaii",
          "USA",
          "Chordata"],
        "informalClassification":["Chaetodon",
          "multicinctus"],
        "samplingPurpose":["genomic analysis"],
        "producedBy_label":"tissue subsample from CMU_161",
        "producedBy_isb_core_id":"ark:/21547/BIE2391b18d0c39141193a2379f36b77e539",
        "producedBy_samplingSite_label":"French Frigate Shoals",
        "producedBy_samplingSite_placeName":["French Frigate Shoals",
          "Hawaii",
          "USA"],
        "producedBy_samplingSite_location_ll":"23.7502778,-166.1666667",
        "producedBy_samplingSite_location_bb":"ENVELOPE(-166.1666667, -166.1666667, 23.7502778, 23.7502778)",
        "producedBy_samplingSite_location_rpt":"POINT (-166.1666667 23.7502778)",
        "relatedResource_isb_core_id":["ark:/21547/mx2CMU_161"],
        "source":"GEOME",
        "producedBy_samplingSite_location_bb__minY":23.7502778,
        "producedBy_samplingSite_location_bb__maxX":-166.1666667,
        "_version_":1712274571226251264,
        "producedBy_samplingSite_location_bb__minX":-166.1666667,
        "producedBy_samplingSite_location_bb__maxY":23.7502778}]
  }
```

**Comment by dannymandel** [comment]
However, if you look for the parent, you can see it's there in the core record here: ` "producedBy_isb_core_id":"ark:/21547/BIE2391b18d0c39141193a2379f36b77e539"`

**Comment by dannymandel** [comment]
On the Solr side, we end up with 2 records:
(1) melding the parent (sampling event) and main record (you can see the main record pointing to the parent sampling event in `"producedBy_isb_core_id":"ark:/21547/BIE2391b18d0c39141193a2379f36b77e539"`)
(2) the child subsample record pointing back to the main record (you can see the child pointer back to main record in `"relatedResource_isb_core_id":["ark:/21547/mx2CMU_161"` and the child pointer back to the parent sampling event in `"producedBy_isb_core_id":"ark:/21547/BIE2391b18d0c39141193a2379f36b77e539"`)

So, a couple questions:
(1) if we wanted to find the parent (sampling event) using its ARK, should we make that work (currently doesn't)
(2) should we make the child findable via the Things API (currently doesn't)?

**Comment by dannymandel** [comment]
Other collections should be reviewed as well, but kicking off the discussion for GEOME here.

**Comment by dannymandel** [comment]
I think it would be helpful using the record above to break down the use cases and the expected outcomes.

Identifier | Record type | Output of searching Things | Output of searching Solr | How to implement
------------ | ------------- | ------------- | ------------- | -------------
ark:/21547/mx2CMU_161 | Sample | Full record, with pointers in both directions | Full record, with pointers in both directions | Done 
ark:/21547/BIF2CMU_161 | Tissue | Currently, 404 | Child record, with pointers to parent and event | Hook up the existing child record transformer to Things API.  Need to come up with a scheme for finding the child record in Things DB as it is currently impossible.
(Event GUID) | Event | Currently, 404 | Currently, 404 | Need an event transformer to core metadata scheme.  Need a way to find the parent record in Things DB as it is currently impossible.  When we build the Solr API, we'll need to build something to query by the `producedBy_isb_core_id ` field, as it's already part of the sample and tissue documents.

**Comment by dannymandel** [comment]
In looking at the requirements for the child solr record, I do think we need the full JSON, because the child metadata record is really a blend of sample, tissue, and event.

In looking at the requirements for the event record (if we wanted to have a pointer to the sample), we'd need to store the ARK for the sample somewhere in the event JSON.  I wonder if it makes sense to break out the JSON to its own table and normalize it off the Thing -- then we'd end up with 3 Thing rows and one JSON row.

**Comment by dannymandel** [comment]
Per discussion with @datadavev -- the official plan of record is to revive the `Relation` table.  For GEOME, we'll have the following tuples 
```
{s=event ARK, p=has_record, o=Thing _id}
{s=tissue ARK, p=has_record, o=Thing _id}
```

We'll also record alternate OpenContext IDs in this manner, with:

```
{s=OpenContext ID, p=has_record, o=Thing _id}
```

There are a few pieces involved in this change:

1. Convert the Relation model to SQLModel and verify it works
2. Backport the existing Things schema to the new model by iterating existing Things and inserting new Relations
3. Change the ingestion code to also create the new Relations as we create new records
4. Change the querying code (mainly in the Things API) to fall back to the Relation table if we don't find a Thing by id
5. For GEOME, determine which transformer to use once we've fetch the Thing record -- this will involve iterating the possible slots and locating the correct type of record then choosing the appropriate GEOME transformer
6. Writing the GEOME event transformer -- should be pretty simple

**Comment by datadavev** [comment]
After some further consideration, it seems there are two types of functionality needed:

1. Given a globally unique identifier (GUID), return the corresponding record that was retrieved from the source collection.
2. Given an GUID (and possibly a relation type), return GUIDs for related things (and possibly the corresponding records). 

Although (1) is similar to (2), the key difference is that (1) will always resolve to nothing or a single internal record identifier, whereas (2) may return multiple results and the returned identifiers may reference entities outside of iSamples.

The immediate case of resolving this bug can be resolved by either creating a new table that provides the mapping from globally unique id to internal _id or changing the id column of things to an array type. The former is more portable and so is preferable. It may also be simpler for updates and adding values.

So, the suggestion is to create a new table something like:
```sql
CREATE TABLE identifiers (
  guid character varying PRIMARY KEY,
  _id integer NOT NULL,
  tstamp timestamp with time zone
)
```

This table could include alternate identifiers such as the OpenContext publication IDs or other unique identifiers that point to specific records. For the GEOME record above:

| guid | _id |
| --- | --- |
| ark:/21547/BIE2391b18d0c39141193a2379f36b77e539 | 1234 |
| ark:/21547/mx2CMU_161 | 1234 |
| ark:/21547/BIF2CMU_161 | 1234 |

A fake OpenContext record might have:

| guid | _id |
| --- | --- |
| ark:/1234/oc-id-value | 8888 |
| doi:10.444/pub-id-value | 8888 |

SESAR and SMITHSONIAN would have single entries per record, with IGSN / ARK and corresponding internal id.

The more general case of handling relations still needs to be implemented, but seems separate to resolution of this issue with many different use cases.

**Comment by dannymandel** [comment]
Per discussion over Slack, there's some complexity here.  It looks like the GEOME parent event is present for multiple GEOME samples.  This parent event: `"bcid": "ark:/21547/Duf242514eacdfe6ca78a925008f7c003082"`
is present for Samples `"bcid": "ark:/21547/Due2SERCFISH0206"` and `"bcid": "ark:/21547/Due2SERCFISH0208"`.  So if you  were to ask for a Thing with id `Duf242514eacdfe6ca78a925008f7c003082`, it would be lossy at a minimum to return either `0206` or `0208`.

**Comment by dannymandel** [comment]
The work here was implemented in a number of different pull requests, including 

https://github.com/isamplesorg/metadata/pull/77
https://github.com/isamplesorg/isamples_inabox/pull/73

The core issue is fixed.

**Comment by dannymandel** [comment]
Closing.
