### ISSUE TITLE
Generate sitemap for content

### ISSUE THREAD

**Issue by datadavev** [isamplesorg/isamples_inabox#77]
sitemap.xml documents provide an index to content available on a site and can include properties such as timestamps and content type information for each location advertised.

Implement a mechanism to generate a set of sitemaps (there are limits to the site of a sitemap) based on the current content available. The target content is the iSamples core records.

**Comment by dannymandel** [comment]
Reference material: https://www.sitemaps.org/protocol.html#index
Python Implementation: https://github.com/Haikson/sitemap-generator

**Comment by dannymandel** [comment]
Merged and crontab installed on mars:

```
#!/bin/bash

cd /home/isamples/isamples_inabox
source /home/isamples/.virtualenvs/isb/bin/activate

declare DATE=$(date "+%Y-%m-%d")
declare OUTPUT_DIR="/home/isamples/sitemaps/$DATE/sitemaps"
echo "Attempting to remove sitemap directory output at $OUTPUT_DIR, ok if this fails"
rm -rf $OUTPUT_DIR
echo "Creating sitemap directory output at $OUTPUT_DIR"
mkdir $OUTPUT_DIR
echo "Invoking sitemap creation script"
python scripts/generate_things_sitemap.py -h "http://mars.cyverse.org" -p "$OUTPUT_DIR"  >& /var/log/isamples/$DATE.sitemap.txt
echo "Removing old sitemaps symlink"
rm -rf /home/isamples/isamples_inabox/isb_web/sitemaps
echo "Creating new sitemaps symlink"
ln -s $OUTPUT_DIR /home/isamples/isamples_inabox/isb_web/
```

**Comment by dannymandel** [comment]
Index available at https://mars.cyverse.org/sitemaps/sitemap-index.xml
