### ISSUE TITLE
Add text "bucket" field for general search

### ISSUE THREAD

**Issue by datadavev** [isamplesorg/isamples_inabox#82]
A common use case for search is looking for a term that appears somewhere in a record (google-ish search).

This is best facilitated by bundling text from various fields into a single field, probably simplest to use copy field operations for this. Field type may be `text_general` or perhaps `text_en`.

**Comment by datadavev** [comment]
Fields to include:

- source
- description
- label
- keywords
- informalClassification
- producedBy_label
- producedBy_description
- producedBy_hasFeatureOfInterest
- producedBy_responsibility
- producedBy_samplingSite_description
- producedBy_samplingSite_placeName
- producedBy_samplingSite_label
- registrant
- samplingPurpose
- curation_label
- curation_description
- curation_location

**Comment by dannymandel** [comment]
Fixed by #90
