### ISSUE TITLE
Summarize the text parsing being used in solr and the configuration options available

### ISSUE THREAD

**Issue by datadavev** [isamplesorg/isamples_inabox#99]
There are many configurable options for the various fields being used in solr, especially the text fields.

The goal of this task is to summarize the types of text field that are currently in use, provide cross references to documentation, and review configuration options for possible changes that may further benefit discovery for the types of content being used in iSamples

**Comment by dannymandel** [comment]
Looks like this is how our text field is currently configured:

```
{
        "name":"text_en",
        "class":"solr.TextField",
        "positionIncrementGap":"100",
        "indexAnalyzer":{
          "tokenizer":{
            "class":"solr.StandardTokenizerFactory"},
          "filters":[{
              "class":"solr.StopFilterFactory",
              "words":"lang/stopwords_en.txt",
              "ignoreCase":"true"},
            {
              "class":"solr.LowerCaseFilterFactory"},
            {
              "class":"solr.EnglishPossessiveFilterFactory"},
            {
              "class":"solr.KeywordMarkerFilterFactory",
              "protected":"protwords.txt"},
            {
              "class":"solr.PorterStemFilterFactory"}]},
        "queryAnalyzer":{
          "tokenizer":{
            "class":"solr.StandardTokenizerFactory"},
          "filters":[{
              "class":"solr.SynonymGraphFilterFactory",
              "expand":"true",
              "ignoreCase":"true",
              "synonyms":"synonyms.txt"},
            {
              "class":"solr.StopFilterFactory",
              "words":"lang/stopwords_en.txt",
              "ignoreCase":"true"},
            {
              "class":"solr.LowerCaseFilterFactory"},
            {
              "class":"solr.EnglishPossessiveFilterFactory"},
            {
              "class":"solr.KeywordMarkerFilterFactory",
              "protected":"protwords.txt"},
            {
              "class":"solr.PorterStemFilterFactory"}]}},
```

**Comment by dannymandel** [comment]
Upon further examination, we were actually using the `text_general` field type, which has the following config:

```
        "indexAnalyzer":{
          "tokenizer":{
            "class":"solr.StandardTokenizerFactory"},
          "filters":[{
              "class":"solr.StopFilterFactory",
              "words":"stopwords.txt",
              "ignoreCase":"true"},
            {
              "class":"solr.LowerCaseFilterFactory"}]},
```

**Comment by dannymandel** [comment]
So, the first change we should make is to switch over to `text_en`.

**Comment by dannymandel** [comment]
The following is the list of the filter factories for `text_en`:

| Name | Config | Explanation of what it does | Recommended next steps |
| --- | --- | --- | --- |
| SynonymGraphFilterFactory | synonyms.txt | Generates synonyms at query time -- substituting words to search for | https://github.com/isamplesorg/isamples_inabox/issues/98 |
| StopFilterFactory | lang/stopwords_en.txt | Discards tokens both at index and query time | https://github.com/isamplesorg/isamples_inabox/issues/97 |
| LowerCaseFilterFactory | None | Converts tokens to lowercase for searching | None |
| EnglishPosessiveFilterFactory | None | Handles possessives, e.g. Danny's -> Danny | None |
| KeywordMarkerFilterFactory | protwords.txt | Prevents terms from being stemmed by the stem filter | Think about this one --  are there any words we don't want stemmed? | 
| PorterStemFilterFactory | None | Does English language stemming, e.g. Analyzer -> Analyze | None |

**Comment by dannymandel** [comment]
Converted the field types on mars.cyverse.org, and a reindex is in process.

**Comment by dannymandel** [comment]
Also, updated the index creation script: https://github.com/isamplesorg/isamples_inabox/pull/101

**Comment by dannymandel** [comment]
General list of all the default options is here: https://solr.apache.org/guide/8_10/filter-descriptions.html

**Comment by dannymandel** [comment]
Post-reindex, the English stop words no longer show up in the facet query for `searchText`:

http://localhost:8984/solr/isb_core_records/select?facet.field=searchText&facet=on&q=*%3A*&rows=0&facet=true

**Comment by dannymandel** [comment]
For reference, this is how you change the field type using the REST API:

```
mandeld@SBS-7448 metadata % curl -X POST -H 'Content-type:application/json' --data-binary '{                                                 
  "replace-field":{
     "name":"searchText",
     "type":"text_en",
     "stored":true,
     "indexed":true,
     "multiValued":true
  }
}' http://localhost:8984/solr/isb_core_records/schema
```

**Comment by dannymandel** [comment]
As far as I can tell, two big pieces that we aren't currently utilizing but could are:

(1) Phonetic matching -- not sure if it's worth exploring, this is more if we are trying to match spoken words to search results
(2) NLP integration -- details here: https://solr.apache.org/guide/7_3/language-analysis.html#opennlp-integration

**Comment by dannymandel** [comment]
Note that when updating the config for the running collection, we need to update it in zookeeper.  Here's an example of one I changed to update the protected words file:

```
bin/solr zk cp file:/opt/solr/server/solr/configsets/_default/conf/protwords.txt zk:/configs/isb_core_records/protwords.txt -z localhost:2181/solr
```

**Comment by dannymandel** [comment]
This issue is a good summary of everything we are using.  Closing it since there is no more work to be done for the moment.
